import = [
  "~/.config/alacritty/colors.toml",
  "~/.config/alacritty/keybindings.toml",
]

live_config_reload = true
working_directory = "None"

[shell] 
program = "/bin/zsh"

[cursor]
vi_mode_style = "Block"

[cursor.style]
blinking = "Off"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 21

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.offset]
x = 0
y = 1

[scrolling]
history = 10000

[window]
decorations = "none"
dynamic_padding = false
startup_mode = "Windowed"
title = "Alacritty"

[window.padding]
x = 6
y = 6
