cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/versions"
tap "homebrew/core"

brew "avro-tools"
brew "bat"
brew "brew-cask-completion"
brew "coreutils"
brew "ctags"
brew "ffmpeg"
brew "fish"
brew "fzf"
brew "git"
brew "git-secrets"
brew "htop"
brew "hub"
brew "jq"
brew "lastpass-cli"
brew "macvim"
brew "mysql"
brew "n"
brew "node"
brew "phpunit"
brew "reattach-to-user-namespace"
brew "redis"
brew "sbt"
brew "shellcheck"
brew "telnet"
brew "tmux"
brew "wget"

cask "iTerm2"
cask "google-chrome"
cask "jetbrains-toolbox"
cask "java8"
cask "alfred"
cask "bettertouchtool"
cask "karabiner-elements"
cask "virtualbox"
cask "vagrant"
cask "spectacle"
cask "visual-studio-code"
cask "docker"
cask "dropbox"
cask "google-backup-and-sync"
cask "cheatsheet"

mas "LastPass", id:  926036361
mas "Slack", id: 803453959 
mas "WhatsApp Desktop", id: 1147396723 

