require('settings.options')
require('settings.remaps')
require('plugins')
require('settings.colorscheme')
require('settings.cmp').setup()
require('settings.lsp').setup()
require('settings.telescope').setup()
require('settings.treesitter').setup()
require('settings.autopairs').setup()
require('settings.signify').setup()
require('settings.nvim-tree').setup()
require('settings.lualine').setup()
require('settings.vim-test')
require('settings.notify').setup()
require('settings.dap').setup()
require('settings.metals').setup()


